### ISSUE TITLE
Hides cursor in studio when mouse button is down shouldn't be a "fix", but a feature.

### ISSUE THREAD

**Issue by wits-fe** [IllusionMods/IllusionFixes#10]
Hiding cursor sometimes makes me mistake like clicking something else.
Is it possible that adds an option similar to "Manage cursor in maker", which is in Maker Optimizations settings, to toggle hides or not cursor in studio?

**Comment by ManlyMarco** [comment]
It seems that generally people prefer the "fixed" way. You can disable it by removing Fix_CameraTarget.dll. For now closing the issue with no fix.
