### ISSUE TITLE
Bug with FK and characters parented to left hand

### ISSUE THREAD

**Issue by DeathWeasel1337** [IllusionMods/IllusionFixes#12]
Characters with another character set as a child of the left hand will break FK when the parent character is replaced.

Steps to reproduce:

- Enable FK for character 1
- Set character 2 as child of character 1's left hand
- Replace character 1

This causes the right arm FK to reset to the animation default and modifying any FK nodes on the right arm affects character 2 instead of character 1. Attached is a scene with this set up, replace the male character to see the bug in action.

![2020_0306_1120_02_512](https://user-images.githubusercontent.com/37981563/76107830-17aeec80-5f9f-11ea-9889-b30f4d0cb55b.png)

Tested on Koikatsu with no plugins installed so it appears to be a vanilla game bug

**Comment by ManlyMarco** [comment]
~~Should be fixed by now.~~ Is not

**Comment by DeathWeasel1337** [comment]
Fixed in b393afa and 86f4811
