### ISSUE TITLE
SettingsVerifier Config.Start is missing.

### ISSUE THREAD

**Issue by jojorne** [IllusionMods/IllusionFixes#15]
HS2_Fix_SettingsVerifier.dll -> Config.Start is missing. Found Initialize instead.

**Comment by ManlyMarco** [comment]
It's already fixed in master https://github.com/IllusionMods/IllusionFixes/commit/ec888d2bb3875bca1e6810ed9cd63c14f13ef7cf

**Comment by ManlyMarco** [comment]
Fix released.
