### ISSUE TITLE
Incorrect FK node orientation on scene load

### ISSUE THREAD

**Issue by DeathWeasel1337** [IllusionMods/IllusionFixes#16]
Game: Koikatsu, AI Girl, Honey Select 2, possibly older Illusion games as well

Steps to reproduce:
Add a character to a scene, enabled FK mode, select a shoulder node.
![Koikatu-2020-07-28-17-42-38-UI](https://user-images.githubusercontent.com/37981563/88729819-5bdf8c80-d0fa-11ea-80bb-36e635388c7a.png)

Rotate the character, select the shoulder node. Note how the guide object is rotated along with the character, green arrow still aligned with the body.
![Koikatu-2020-07-28-17-42-48-UI](https://user-images.githubusercontent.com/37981563/88729916-86314a00-d0fa-11ea-9b7f-351053d744e3.png)

Save the scene and reload. Select the shoulder node. Note how it is no longer aligned with the body, green arrow pointing straight up instead.
![Koikatu-2020-07-28-17-43-04-UI](https://user-images.githubusercontent.com/37981563/88729957-9f39fb00-d0fa-11ea-8187-4f7d496c5350.png)

Reset rotation of the character. Guide object rotates along with the character, but because the rotation on scene load was incorrect it's still incorrect here, pointing backwards instead of straight upwards.
![Koikatu-2020-07-28-17-43-16-UI](https://user-images.githubusercontent.com/37981563/88730057-d90b0180-d0fa-11ea-88e0-abe13c89aeb2.png)

This is harmless in that it does not impact the pose of the character, however the inconsistent guide object behavior can be annoying.

**Comment by ManlyMarco** [comment]
Attempted to fix, turned out to be surprisingly tricky. Unlikely to get fixed I think.
