### ISSUE TITLE
KK_Fix_CharacterListOptimizations not useful in VR but fixable?

### ISSUE THREAD

**Issue by Geil0mat** [IllusionMods/IllusionFixes#23]
Hello,

I noticed that KK_Fix_CharacterListOptimizations had no measurable impact on load times in the official KoikatuVR. 
KoikatuVR without dll: 34 (26) seconds 
KoikatuVR with dll: 34 (26) seconds
Koikatu without dll: 9 (8) seconds
Koikatu with dll: 3 (3) seconds
(values are for 500 cards, first value is for first load, second value is when coming back from h scene)

Out of curiosity I checked the source. For VR prefix/postfix functions for ClassRoomCharaFileInitializeList are created and hooked, but there is only a postfix for ClassRoomCharaFileStart.

I created and hooked a prefix for ClassRoomCharaFileStart, where I set ExtendedSave.LoadEventsEnabled to false. (and set it back to true at the beginning of the postfix) VR load times are now down to 12 (9) seconds.

Is there a reason for not disabling ExtendedSave loadevents during ClassRoomCharaFileStart? (a.k.a. Do I break something with my fix?)

[CharacterListOptimizations.txt](https://github.com/IllusionMods/IllusionFixes/files/5748074/CharacterListOptimizations.txt)

**Comment by ManlyMarco** [comment]
Try this build, looks like the patch is wrong since InitializeList doesn't exist in VR.
[KK_Fix_CharacterListOptimizations.zip](https://github.com/IllusionMods/IllusionFixes/files/5749156/KK_Fix_CharacterListOptimizations.zip)

Hopefully fixed in https://github.com/IllusionMods/IllusionFixes/commit/f6c89f2cc298ddef64021cc7d8b3f3567cae0e7d

**Comment by Geil0mat** [comment]
It's working now. Load times are the same as with my version.

**Comment by ManlyMarco** [comment]
Nice, if you see any other issues let me know.
