### ISSUE TITLE
[KK]Can IK be disabled in the main game?

### ISSUE THREAD

**Issue by ShorneHua** [IllusionMods/IllusionFixes#24]
If I use ABMX to change the length of legs, the characters will be strange because of IK.

![](https://github.com/ShorneHua/MyImages/blob/main/kk1.png?raw=true)

And if I enable "Disable IK in maker" in Maker Optimizations, the character will behave normally.(Though the feet are under the floor, I think it's much more acceptable.)

![](https://github.com/ShorneHua/MyImages/blob/main/kk2.png?raw=true)

But I didn't found a "Disable IK in main game" option. Could you add one please? I would appreciate it a lot!

**Comment by ManlyMarco** [comment]
Disabling it outside of maker would to some degree break animations, you should create the character with the optimization turned off to see how it will look outside of maker (IK off is applicable only to studio). You have to adjust different sliders to get the long leg effect, it's not too difficult and there are guides for this on the discord server.

**Comment by ShorneHua** [comment]
Well, in fact, I don't aim to change the length of legs. It's just an example. Actually I want to do some r18g things.
I know disabling IK may make the game terrible, but I'm just so curious about what will happen if I do that.
(Sorry for my poor English)

**Comment by ManlyMarco** [comment]
> what will happen if I do that

Mostly floating and broken character alignments in H scenes.

**Comment by ShorneHua** [comment]
Thank you very much. I'll try to find other solutions.
