### ISSUE TITLE
Tried updating BepInEx for Koikatsu mod purposes, lost English Translation

### ISSUE THREAD

**Issue by TecFrost** [IllusionMods/IllusionFixes#31]
I wanted to update the BepInEx folder to fix some bugs for character accessory mods. (ex. Sucrose from Genshin Impact and others).
Upon replacing files with what was provided for updating BepInEx, Koikatsu has completely lost it's English translation. 
What happened? How do I fix it?
[I made a backup of everything before attempting the update so I'm good on that front if I need to start from square one]

**Comment by ManlyMarco** [comment]
Probably wrong version of BepInEx, KK needs the 5.x 64bit version. It's better to ask general questions like this on the discord server https://discord.gg/hevygx6.
