### ISSUE TITLE
[KKS] Main Game Optimizations causing "stiff" characters mid-scene

### ISSUE THREAD

**Issue by Avvilimento** [IllusionMods/IllusionFixes#34]
I have noticed that some of the animation on the girls within a sex scene ceases under some circumstances, most notably the hair and breasts. Following some experimentation I've been able to narrow it down to the various dynamic bone update features provided by the main game optimizations. My theory is that these optimizations are remaining in effect during the scene but the character and camera positions used to determine what, if any throttling of the dynamic bone calculations is to be done is still based on their "world" positions. As such, as soon as the "action" moves too far away from the starting point or would otherwise be obscured (depending upon which optimizations are in use) the dynamic bones simply stop.

Given the nature of the optimizations and the scenes involved it would make more sense that they simply be disable during such scenes, rather than attempting to dynamically update the player and camera locations. This would allow for the retention of the optimization outside of the scenes to improve frame rates without any edge cases needing to be catered for.

Testing conducted with BepinEx v5.4.19 and Illusion Fixes v19.2.

**Comment by ManlyMarco** [comment]
Can you check if this build fixes the issue? [KKS_Fix_MainGameOptimizations.zip](https://github.com/IllusionMods/IllusionFixes/files/8327171/KKS_Fix_MainGameOptimizations.zip)

**Comment by Avvilimento** [comment]
Unfortunately it doesn't appear to have fixed the issue. To be honest my brief testing didn't show any difference at all, though this time I did at least confirm that adjusting the range would indeed cause or correct the issue without adjusting the scene or changing position.

In the interest of full disclosure (though you likely already suspected as much) I am running the base "BetterRepack" R3, with Stiletto enabled (though disabling it makes no difference).

**Comment by ManlyMarco** [comment]
I think I've got it, this one should work. [KKS_Fix_MainGameOptimizations.zip](https://github.com/IllusionMods/IllusionFixes/files/8333752/KKS_Fix_MainGameOptimizations.zip)

**Comment by Avvilimento** [comment]
Not a fully comprehensive test by any means, and the non-deterministic nature of the game means I couldn't replicate identical circumstances, but it looks very promising. Adjusting the range caused no problems and a few quick tests suggested starting camera angle wasn't causing issues either.
