### ISSUE TITLE
Lagging in school mode

### ISSUE THREAD

**Issue by StopTheRussian** [IllusionMods/IllusionFixes#39]
I have some some laggings in school mode when the game loading or rotate cam and character moving.

**Comment by ManlyMarco** [comment]
Send your output_log.

**Comment by StopTheRussian** [comment]
[output_log.txt](https://github.com/IllusionMods/IllusionFixes/files/9131180/output_log.txt)

**Comment by ManlyMarco** [comment]
Nothing obvious, try removing FreeHDefaults and reduce max number of characters. You can also try increasing memory optimization threshold in plugin settings of ResourceUnloadOptimizations. Worst case, switch to KKS.
