### ISSUE TITLE
White screen in school mode 

### ISSUE THREAD

**Issue by StopTheRussian** [IllusionMods/IllusionFixes#40]
I fixed the lag but now my screen is completely white 
![Screenshot (48)](https://user-images.githubusercontent.com/100501041/179578649-0efe33d4-d229-415e-951f-dae70a78633f.png)

**Comment by ManlyMarco** [comment]
Can you ask in #help channel on the Koiaktsu discord server? It's likely an issue with your install and not a bug in any plugin from here.
