### ISSUE TITLE
[KK] InvalidSceneFileProtection creates long boot times on many Scenes.

### ISSUE THREAD

**Issue by leoftm** [IllusionMods/IllusionFixes#43]
In environments where InvalidSceneFileProtection.dll is present, the presence of a very large number of scene files can cause a multiplicative slowdown in the startup of CharaStudio.
It takes several minutes in an environment with more than 3000 files, but it takes less than ten seconds when KK_InvalidSceneFileProtection.dll is disabled.

**Comment by ManlyMarco** [comment]
You can avoid the issue by sorting your scenes into folders. The scene files are read to verify that they are valid which will take some time.
Edit: It looks like at some point the preemptive checks were taken out so there should be no performance hit at studio start, make sure you have the latest version of the plugin.
