### ISSUE TITLE
Issue (allegedly) with SceneStack<Data> while trying to load Koikatsu Party with BetterPack

### ISSUE THREAD

**Issue by LeoAidan** [IllusionMods/IllusionFixes#66]
The console gives the following error output:
[Error : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
bool IllusionFixes.GarbageTruck+AntiGarbageHooks.GarbagelessOverlap(SceneStack<Data>, bool)
bool Manager.Scene+<LoadSet>c__Iterator0.MoveNext()
void UnityEngine.SetupCoroutine.InvokeMoveNext(IEnumerator, IntPtr)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Manager.<LoadStart>c__Iterator8:MoveNext()
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Manager.Scene:LoadReserve(Data, Boolean)
<Start>c__Iterator0:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[Error : Unity Log] ArgumentNullException: Argument cannot be null.
Parameter name: source
Stack trace:
bool System.Linq.Enumerable.Any<Data>(IEnumerable<Data>)
bool Manager.Scene+<LoadStart>c__Iterator8.MoveNext()
void UnityEngine.SetupCoroutine.InvokeMoveNext(IEnumerator, IntPtr)

I'm not sure if this is an issue or there's something wrong on my and, but I tried everything and couldn't get it to work.
Also, sorry if this doesn't fall under the "issues" category, I just couldn't find anywhere else where I could report this/ask for help.

**Comment by ManlyMarco** [comment]
Remove KK_Fix_GarbageTruck and try again.

**Comment by LeoAidan** [comment]
Thank you very much for your reply. The error output seems to have changed,
now it's this:
[Error  : Unity Log] ArgumentNullException: Argument cannot be null.
Parameter name: source
Stack trace:
bool System.Linq.Enumerable.Any<Data>(IEnumerable<Data>)
bool Manager.Scene.get_IsOverlap()
bool Manager.Scene+<LoadSet>c__Iterator0.MoveNext()
void UnityEngine.SetupCoroutine.InvokeMoveNext(IEnumerator, IntPtr)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Manager.<LoadStart>c__Iterator8:MoveNext()
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Manager.Scene:LoadReserve(Data, Boolean)
<Start>c__Iterator0:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[Error  : Unity Log] ArgumentNullException: Argument cannot be null.
Parameter name: source
Stack trace:
bool System.Linq.Enumerable.Any<Data>(IEnumerable<Data>)
bool Manager.Scene+<LoadStart>c__Iterator8.MoveNext()
void UnityEngine.SetupCoroutine.InvokeMoveNext(IEnumerator, IntPtr)

**Comment by ManlyMarco** [comment]
In this case this is not a problem with a plugin but with your game install. Install a clean version of the game from the store/disc and try again.

**Comment by LeoAidan** [comment]
I don't have the steam version, but I thought that SB BetterPack (full ed)
had the dlc and everything? If I were to find the installation files on
SteamUnlocked, which would I need to delete from the already installed
files?
Thank you so much for your help btw.

**Comment by ManlyMarco** [comment]
I can't really help you with repacks, sorry. I suggest installing a clean version of the game and using HF Patch or adding mods by hand.

**Comment by LeoAidan** [comment]
I did just that and now everything works, thanks!
